### ISSUE TITLE
Keybinds out of date

### ISSUE THREAD

**Issue by Ramblurr** [Lazy-Newb-Pack/LNP-shared-core#19]
The keybinds in this repo aren't the same ones included with the Windows starter pack. @PeridexisErrant  did you just rename them or are they substantially different?

Since the Linux (and Mac?) packs build from this repo, it would be nice to propagate those changes back here.

**Comment by lethosor** [comment]
I also seem to have push access here, so if you can point me to the new versions of the files, I can update them here. (A pull request would also work, of course)

**Comment by Ramblurr** [comment]
Thanks lethosor, I don't know if PE has his files for the win starter pack public somewhere. You could get them from the keybinds folder of the win starter pack.

**Comment by lethosor** [comment]
https://github.com/PeridexisErrant/starter-pack/tree/master/base/keybinds is outdated, unfortunately. If you have a copy of that pack handy, I'd appreciate the keybindings files so I don't have to download the whole thing. Otherwise, I'll get around to this later.
