### ISSUE TITLE
Game crashes after intro message after embarking

### ISSUE THREAD

**Issue by HeartAttackGorilla** [Lazy-Newb-Pack/LNP-shared-core#20]
After embarking and after the introduction message that begins the story the game is crashing because of a broken reference to the `PyLNP.user` file. I was able to fix it by moving `PyLNP.user` from the root directory of the project to the `/LNP` folder. Could I put in a PR with this fix?

**Comment by lethosor** [comment]
I'm not seeing a `PyLNP.user` file in this project - are you sure you reported this in the right place?

Also, do you have an error message? Typically a crash on embark would be due to something like TWBT. A missing file causing a crash would probably be a bug that should be reported upstream to whatever is crashing.

**Comment by Pidgeot** [comment]
PyLNP.user is the preference file generated by the launcher, PyLNP, when you run it. It's going to be local to your computer, but everything in it is only used by the launcher itself - the game shouldn't even be *trying* to read it, so it sounds like something else must be going on here.

**Comment by HeartAttackGorilla** [comment]
I was suspicious it was a generated file. Let me replicate the issue and report back with the logs.

**Comment by HeartAttackGorilla** [comment]
Sorry for the false alarm. I unzipped the project from scratch and everything worked perfectly.

The stderr file was generated by PyLNP and was only a warning. The logs are:

```
Running PyLNP 0.14a (OS: win, Compiled: True)
WARNING: JSONConfiguration: File PyLNP.user does not exist
INFO: Installing extras content for first time
INFO: Read installed graphics (Phoebus) from log
INFO: Vettlingr graphics added (small mod compatibility risk)
INFO: Safely updated graphics raws .\Dwarf Fortress 0.47.05\raw to Vettlingr
INFO: Loading colorscheme .\LNP\Graphics\Vettlingr\data\init\colors.txt
INFO: Read installed graphics (Vettlingr) from log
INFO: Read installed graphics (Vettlingr) from log
```

Sorry for posting this in the wrong project :/

Not sure what was causing the crash earlier and why it magically started working after moving the `.user` file. I blame the code gnomes.

**Comment by HeartAttackGorilla** [comment]
False alarm.
